function [initialObservation, initialState] = rlResFunc
% Episode reset. Every episode starts from a network that has already run
% 60 steps without control, so the agent always begins in congested traffic
% rather than on an empty road.

%That warm-up was done once by train_RL_MPC.m and stored in net_init.mat.
net_init_vals = load('net_init.mat');
xx = net_init_vals.x;
uu = net_init_vals.u;
kk = net_init_vals.k;
scenario = net_init_vals.scenario;

x_norm = calc_x_norm();

[demando1c1,demando1c2]  = demando1(kk-1,scenario);
[demando2c1,demando2c2]  = demando2(kk-1,scenario);
[demando3c1,demando3c2]  = demando3(kk-1,scenario);


initialState = [xx;...
    [demando1c1,demando1c2]';...
    [demando2c1,demando2c2]';...
    [demando3c1,demando3c2]';...
    uu(2:3); uu(1); kk; scenario; uu(1); uu(1)]; %last terms are for the previous MPC action trajectory to be used as an initial guess for the next MPC computation

% initialObservation = [xx; uu(1:2); uu(9:12);...
%     [demando1c1_1,demando1c1_2,demando1c1_3]';...
%     [demando1c2_1,demando1c2_2,demando1c2_3]';...
%     [demando2c1_1,demando2c1_2,demando2c1_3]'; 
%     [demando2c2_1,demando2c2_2,demando2c2_3]';...
%     [demando3c1_1,demando3c1_2,demando3c1_3]';...
%     [demando3c2_1,demando3c2_2,demando3c2_3]';...
%     k_shift];

initialObservation = [xx./x_norm;...
                     [demando1c1,demando1c2]'./1000;...
                     [demando2c1,demando2c2]'./1000;...
                     [demando3c1,demando3c2]'./1000];

end

